### ISSUE TITLE
Laravel 5.3 support ?

### ISSUE THREAD

**Issue by 0xlemi** [websightgmbh/l5-google-cloud-storage#8]
Does this work with laravel 5.3 ?

**Comment by cedricziel** [comment]
Hey Luis!

As far as I know, there's no problem, since this is a very simple provider. I've started a new (personal) project to wire Google Cloud Storage through a more high level library than the the flysystem driver this project uses.

I recommend to check it out: https://github.com/cedricziel/flysystem-gcs

I've written a few lines about wiring it with laravel so you can do it yourself easily.

To use this project with laravel 5.3, we would just need to Update the composer constraints. Care to send a PR? :)

**Comment by cedricziel** [comment]
Thx to @duffyboyo for spending time on the PR :)

Closing this via #9, released as v1.1.0
